modLoader="javafml" 
loaderVersion="[35,)" 
license="All rights reserved"

[[mods]]
modId="firstmod"
version="1.0"
displayName="First Mod"
credits="Hello"
authors="Dreckigesname"
description='''
Hello
Hallo
Bonjour
Hola
Konichwia
'''